version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: facemenow-postgres
    restart: always
    environment:
      POSTGRES_USER: facemenowuser
      POSTGRES_PASSWORD: facemenowpassword123456
      POSTGRES_DB: facemenowdb
    ports:
      - "5555:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-12-07T04-16-00Z.fips
    container_name: facemenow-minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   
      - "9001:9001"   
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
